// Demo products - Will be replaced by CJ Dropshipping API data
export interface Product {
  id: string;
  slug: string;
  name: string;
  description: string;
  price: number;
  comparePrice?: number;
  image: string;
  images: string[];
  category: string;
  categorySlug: string;
  tag?: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  features: string[];
  deliveryDays: string;
}

export const CATEGORIES = [
  { name: 'Maison & Déco', slug: 'maison-deco', emoji: '🏠', count: 4, color: 'from-blue-500 to-indigo-600' },
  { name: 'Beauté & Santé', slug: 'beaute-sante', emoji: '✨', count: 3, color: 'from-pink-500 to-rose-600' },
  { name: 'Tech & Gadgets', slug: 'tech-gadgets', emoji: '📱', count: 3, color: 'from-violet-500 to-purple-600' },
  { name: 'Animaux', slug: 'animaux', emoji: '🐾', count: 2, color: 'from-amber-500 to-orange-600' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod_001',
    slug: 'sunset-lamp-projection',
    name: 'Lampe Sunset Projection',
    description: 'Transformez votre intérieur avec cette lampe de projection coucher de soleil. Créez une ambiance chaleureuse et relaxante dans n\'importe quelle pièce. Rotation 360° pour un éclairage personnalisé.',
    price: 34.99,
    comparePrice: 59.99,
    image: '🌅',
    images: ['🌅', '🌇', '🏠'],
    category: 'Maison & Déco',
    categorySlug: 'maison-deco',
    tag: 'Tendance',
    rating: 4.8,
    reviewCount: 342,
    inStock: true,
    features: ['Rotation 360°', 'USB rechargeable', 'LED longue durée', '4 filtres couleur inclus'],
    deliveryDays: '5-12',
  },
  {
    id: 'prod_002',
    slug: 'galaxy-projector-stars',
    name: 'Projecteur Galaxy Étoiles',
    description: 'Projetez un ciel étoilé dans votre chambre avec ce projecteur galaxy nouvelle génération. Télécommande incluse, minuterie automatique, et 15 modes d\'éclairage.',
    price: 42.99,
    comparePrice: 69.99,
    image: '🌌',
    images: ['🌌', '⭐', '🌙'],
    category: 'Maison & Déco',
    categorySlug: 'maison-deco',
    tag: 'Best-seller',
    rating: 4.7,
    reviewCount: 518,
    inStock: true,
    features: ['15 modes éclairage', 'Télécommande incluse', 'Minuterie auto', 'Bluetooth speaker'],
    deliveryDays: '5-12',
  },
  {
    id: 'prod_003',
    slug: 'fer-lisser-sans-fil',
    name: 'Fer à Lisser Sans Fil',
    description: 'Lisseur professionnel sans fil avec batterie rechargeable longue durée. Plaques en céramique tourmaline pour des cheveux soyeux sans dommage. Chauffe en 30 secondes.',
    price: 45.99,
    comparePrice: 79.99,
    image: '💇‍♀️',
    images: ['💇‍♀️', '✨', '🔋'],
    category: 'Beauté & Santé',
    categorySlug: 'beaute-sante',
    tag: 'Nouveau',
    rating: 4.6,
    reviewCount: 189,
    inStock: true,
    features: ['Sans fil rechargeable', 'Céramique tourmaline', 'Chauffe en 30s', '3 températures'],
    deliveryDays: '5-12',
  },
  {
    id: 'prod_004',
    slug: 'mini-projecteur-portable',
    name: 'Mini Projecteur Portable',
    description: 'Projecteur HD portable pour smartphone. Profitez d\'un écran cinéma de 120" partout. Compatible WiFi, HDMI, USB. Batterie intégrée 2h d\'autonomie.',
    price: 69.99,
    comparePrice: 119.99,
    image: '🎬',
    images: ['🎬', '📽️', '📱'],
    category: 'Tech & Gadgets',
    categorySlug: 'tech-gadgets',
    tag: 'Populaire',
    rating: 4.5,
    reviewCount: 276,
    inStock: true,
    features: ['HD 1080p', 'WiFi intégré', 'Batterie 2h', 'Projection 120"'],
    deliveryDays: '7-15',
  },
  {
    id: 'prod_005',
    slug: 'collier-gps-animal',
    name: 'Collier GPS Tracker Animal',
    description: 'Ne perdez plus jamais votre animal ! Tracker GPS temps réel avec application mobile. Étanche IP67, batterie 7 jours. Zone de sécurité configurable avec alertes.',
    price: 49.99,
    comparePrice: 89.99,
    image: '🐕',
    images: ['🐕', '📍', '📱'],
    category: 'Animaux',
    categorySlug: 'animaux',
    tag: 'Best-seller',
    rating: 4.9,
    reviewCount: 631,
    inStock: true,
    features: ['GPS temps réel', 'Étanche IP67', 'Batterie 7 jours', 'Alertes zone sécurité'],
    deliveryDays: '5-12',
  },
  {
    id: 'prod_006',
    slug: 'masque-led-visage',
    name: 'Masque LED Luminothérapie',
    description: 'Masque facial LED professionnel avec 7 couleurs de luminothérapie. Traite l\'acné, les rides, et améliore le teint. Usage quotidien 15-20 min.',
    price: 54.99,
    comparePrice: 89.99,
    image: '🎭',
    images: ['🎭', '✨', '💆‍♀️'],
    category: 'Beauté & Santé',
    categorySlug: 'beaute-sante',
    tag: 'Tendance',
    rating: 4.4,
    reviewCount: 203,
    inStock: true,
    features: ['7 couleurs LED', 'Anti-acné', 'Anti-rides', 'Usage quotidien 15min'],
    deliveryDays: '7-15',
  },
  {
    id: 'prod_007',
    slug: 'correcteur-posture-intelligent',
    name: 'Correcteur de Posture Intelligent',
    description: 'Correcteur de posture avec vibration intelligente. Détecte automatiquement votre posture et vibre pour vous rappeler de vous redresser. Discret sous les vêtements.',
    price: 29.99,
    comparePrice: 49.99,
    image: '🧘',
    images: ['🧘', '📱', '✅'],
    category: 'Beauté & Santé',
    categorySlug: 'beaute-sante',
    rating: 4.3,
    reviewCount: 157,
    inStock: true,
    features: ['Vibration intelligente', 'App Bluetooth', 'Discret', 'Rechargeable USB'],
    deliveryDays: '5-12',
  },
  {
    id: 'prod_008',
    slug: 'ecouteurs-bluetooth-pro',
    name: 'Écouteurs Bluetooth Pro',
    description: 'Écouteurs sans fil avec réduction de bruit active. Son Hi-Fi, 40h d\'autonomie avec le boîtier, résistant à l\'eau IPX5. Micro intégré pour appels.',
    price: 39.99,
    comparePrice: 69.99,
    image: '🎧',
    images: ['🎧', '🎵', '📱'],
    category: 'Tech & Gadgets',
    categorySlug: 'tech-gadgets',
    tag: 'Populaire',
    rating: 4.6,
    reviewCount: 445,
    inStock: true,
    features: ['Réduction bruit active', '40h autonomie', 'IPX5 waterproof', 'Micro HD'],
    deliveryDays: '5-12',
  },
  {
    id: 'prod_009',
    slug: 'lampe-lune-3d',
    name: 'Lampe Lune 3D Tactile',
    description: 'Reproduction fidèle de la lune imprimée en 3D. 16 couleurs changeantes avec télécommande. Rechargeable USB, toucher tactile pour changer de mode.',
    price: 27.99,
    comparePrice: 44.99,
    image: '🌕',
    images: ['🌕', '🌙', '💡'],
    category: 'Maison & Déco',
    categorySlug: 'maison-deco',
    rating: 4.7,
    reviewCount: 389,
    inStock: true,
    features: ['Impression 3D fidèle', '16 couleurs', 'Tactile', 'USB rechargeable'],
    deliveryDays: '5-12',
  },
  {
    id: 'prod_010',
    slug: 'distributeur-nourriture-animal',
    name: 'Distributeur Automatique Animal',
    description: 'Distributeur de nourriture automatique avec caméra WiFi et micro. Programmez les repas via l\'application. Capacité 4L, portions ajustables.',
    price: 59.99,
    comparePrice: 99.99,
    image: '🐱',
    images: ['🐱', '📱', '🍽️'],
    category: 'Animaux',
    categorySlug: 'animaux',
    tag: 'Nouveau',
    rating: 4.5,
    reviewCount: 98,
    inStock: true,
    features: ['Caméra WiFi', 'App contrôle', 'Capacité 4L', 'Portions ajustables'],
    deliveryDays: '7-15',
  },
  {
    id: 'prod_011',
    slug: 'chargeur-sans-fil-rapide',
    name: 'Chargeur Sans Fil 3-en-1',
    description: 'Station de charge sans fil pour téléphone, montre et écouteurs simultanément. Compatible MagSafe, charge rapide 15W. Design élégant en aluminium.',
    price: 35.99,
    comparePrice: 59.99,
    image: '🔋',
    images: ['🔋', '📱', '⌚'],
    category: 'Tech & Gadgets',
    categorySlug: 'tech-gadgets',
    rating: 4.4,
    reviewCount: 267,
    inStock: true,
    features: ['3-en-1', 'Charge rapide 15W', 'Compatible MagSafe', 'Aluminium premium'],
    deliveryDays: '5-12',
  },
  {
    id: 'prod_012',
    slug: 'humidificateur-flamme',
    name: 'Humidificateur Effet Flamme',
    description: 'Diffuseur d\'huiles essentielles avec effet flamme réaliste. Silencieux, arrêt automatique, 2 modes de brume. Capacité 300ml.',
    price: 32.99,
    comparePrice: 54.99,
    image: '🔥',
    images: ['🔥', '💨', '🏠'],
    category: 'Maison & Déco',
    categorySlug: 'maison-deco',
    tag: 'Tendance',
    rating: 4.6,
    reviewCount: 312,
    inStock: true,
    features: ['Effet flamme réaliste', 'Silencieux', 'Arrêt auto', 'Diffuseur huiles'],
    deliveryDays: '5-12',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return PRODUCTS.filter((p) => p.categorySlug === categorySlug);
}
